---
# tasks file for ansible-role-git
- name: add test users
  ansible.builtin.user:
    name: git_user
    state: present
    shell: /bin/bash
    groups: user
  become: yes
  
- name: add git config files
  ansible.builtin.template:
    src: files/.gitconfig
    dest: "/home/{{item.name}}/.gitconfig"
    owner: git_user
  become: yes
  
- name: create .ssh folders
  ansible.builtin.file:
    path: /home/git_user/.ssh
    state: directory
    mode: '0700'
    owner: git_user
  become: yes
      
- name: add public key
  ansible.builtin.copy:
    src: ./files/authorized_keys
    dest: /home/git_user/.ssh/authorized_keys
    mode: '0600'
    owner: git_user
  become: yes
