# На какой группе серверов
- hosts: webservers

  tasks:
    - name: install redis server
      ansible.builtin.apt:
        name: git
        state: absent
        update_cache: yes
      become: yes # <---

#    - name: remove redis server
#      ansible.builtin.apt:
#        name: redis-server
#        state: absent
#        state: present
#      become: yes # <---
