# На какой группе серверов
- hosts: webservers
  vars:
    nginx_port: 8081
    root_dir: /usr/share/nginx/html/index.html
    server_name: "{{ansible_distribution}}, {{ansible_distribution_version}}"
    date_time: "{{ ansible_date_time['iso8601_micro'] }}"
  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes
      become: yes
      tags: install     

    - name: install cowsay
      ansible.builtin.apt:
        name: cowsay
        state: present
        update_cache: yes
      become: yes
      tags: install 
           
    - name: update nginx config
      ansible.builtin.template:
        src: files/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
      become: yes

    - name: cowsay command
      ansible.builtin.shell: "cowsay This is server {{server_name}}"
      register: cowsay_result
    
    - name: print cowsay_result variable
      ansible.builtin.debug:
        var: cowsay_result
                         
    - name:
      ansible.builtin.template:
        src: files/index.html
        dest: "{{root_dir}}"
      become: yes
     
     
     
      
  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes    


