# На какой группе серверов
- hosts: webservers
  roles:
    - adrianjuhl.git  
    - role: my_roles.user_git
      vars:
        vars_user: { name: git_user1, email: git_user1@test.com }     

    

  tasks:
      



